# -*- coding: utf-8 -*-
"""Assignmentno1.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OePEYM2lbvlc4KLUG69SCxfEIBpf3ZxT
"""

# Commented out IPython magic to ensure Python compatibility.

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
# %matplotlib inline

cars=pd.read_csv("/content/sample_data/Q7.csv")

cars

cars.mean()

cars.median()

cars.Points.mode()

cars.Score.mode()

cars.Weigh.mode()

cars.var()

cars.std()

cars.describe()

Points_Range=cars.Points.max()-cars.Points.min()
Points_Range

Score_Range=cars.Score.max()-cars.Score.min()
Score_Range

Weigh_Range=cars.Weigh.max()-cars.Weigh.min()
Weigh_Range

f,ax=plt.subplots(figsize=(15,5))
plt.subplot(1,3,1)
plt.boxplot(cars.Points)
plt.title('Points')
plt.subplot(1,3,2)
plt.boxplot(cars.Score)
plt.title('Score')
plt.subplot(1,3,3)
plt.boxplot(cars.Weigh)
plt.title('Weigh')
plt.show()

data=pd.read_csv("/content/sample_data/Q9_a.csv")

print(data)

data.skew()

data.kurt()

y=pd.read_csv("/content/sample_data/Q9_b.csv")

print(y)

y.skew()

y.hist()
plt.show()

import numpy as np
import pandas as pd
from scipy import stats
from scipy.stats import norm

stats.norm.interval(0.94,200,30/(2000**0.5))

# Avg. weight of Adult in Mexico with 98% CI
stats.norm.interval(0.98,200,30/(2000**0.5))

# Avg. weight of Adult in Mexico with 96% CI
stats.norm.interval(0.96,200,30/(2000**0.5))

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
# %matplotlib inline

x=pd.Series([34,36,36,38,38,39,39,40,40,41,41,41,41,42,42,45,49,56])

x.mean()

# Median
x.median()

x.var()

x.std()

plt.boxplot(x)

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
# %matplotlib inline

cars=pd.read_csv('/content/sample_data/Cars.csv')
cars

sns.distplot(cars.MPG, label='Cars-MPG')
plt.xlabel('MPG')
plt.ylabel('Density')
plt.legend();

cars.MPG.mean()

cars.MPG.median()

i=pd.read_csv('/content/sample_data/wc-at.csv')
i

from scipy import stats
from scipy.stats import norm

stats.norm.ppf(0.95)

# Z-score of 94% confidence interval
stats.norm.ppf(0.97)

# Z-score of 60% confidence interval
stats.norm.ppf(0.8)

